### ISSUE TITLE
Заменить фильтр логгера `AbstractFilter` из log4j на встроенный `java.util.logging.Filter`

### ISSUE THREAD

**Issue by emberati** [pixplaze/pixplaze-core-plugin#17]

**Comment by emberati** [comment]
Заменить невозможно, так как ядро сервера использует логгер `log4j`, стандартный логгер ничего не знает о сообщениях обработанных этим логгером.

Судя по всему это единственный способ перехватить сообщения консоли сервера.

**Comment by pazik98** [comment]
Ясно, сам с собой поссорился и помирился )
